---
- become: true
  gather_facts: false
  hosts: all
  name: Verify
  tasks:
  - ansible.builtin.lineinfile:
      path: /etc/group
      regex: ^docker:x:\d*:woody,buzz$
      state: absent
    changed_when: not docker_group is changed
    check_mode: true
    failed_when: docker_group is changed
    name: Check docker group configuration
    register: docker_group
  - docker_container:
      image: buluma/docker-centos-openssh
      name: openssh
      ports:
      - '2222:22'
    name: Create a container
    when:
    - ansible_connection not in [ "container", "docker", 
      "community.docker.docker" ]
  - ansible.builtin.command:
      cmd: docker --version
    failed_when:
    - '"podman" in docker_test_one.stdout'
    name: Make sure we are not running podman
    register: docker_test_one
